version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: plastindo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plastindo_inventory
    ports:
      - "5432:5432"
    volumes:
      - plastindo_db_data:/var/lib/postgresql/data

volumes:
  plastindo_db_data:
