version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: plastindo-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plastindo_inventory
    ports:
      - "5432:5432"
    volumes:
      - plastindo_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: plastindo-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plastindo_inventory?schema=public
      - JWT_SECRET=supersecret_jwt_key_plastindo_12345
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=1081464509928-qvuaegjo5dju4tdvb9dq6r4s9rkmrqte.apps.googleusercontent.com
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: plastindo-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  plastindo_db_data:
