-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "itemsPerUnit" DECIMAL(10,2) NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "saleQty" DECIMAL(10,2) NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "saleUnit" TEXT NOT NULL DEFAULT 'buah';
